-- phpMyAdmin SQL Dump
-- version 4.6.5.2
-- https://www.phpmyadmin.net/
--
-- Хост: 127.0.0.1
-- Время создания: Июл 11 2017 г., 15:21
-- Версия сервера: 10.1.21-MariaDB
-- Версия PHP: 5.6.30

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- База данных: `module4`
--

-- --------------------------------------------------------

--
-- Структура таблицы `news`
--

CREATE TABLE `news` (
  `id` int(11) NOT NULL,
  `category` varchar(50) NOT NULL,
  `text` text NOT NULL,
  `analityc` tinyint(1) DEFAULT NULL,
  `description` text,
  `img` varchar(50) NOT NULL,
  `name` varchar(50) NOT NULL,
  `tags` varchar(250) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Дамп данных таблицы `news`
--

INSERT INTO `news` (`id`, `category`, `text`, `analityc`, `description`, `img`, `name`, `tags`) VALUES
(1, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img1.jpg', 'спорт1', 'футбол'),
(2, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img2.jpg', 'спорт2', 'футбол'),
(3, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img3.jpg', 'спорт3', 'футбол'),
(4, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img4.jpg', 'спорт4', 'футбол'),
(5, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img5.jpg', 'спорт5', 'футбол'),
(6, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img6.jpg', 'спорт6', 'футбол'),
(7, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img7.jpg', 'спорт7', 'футбол'),
(8, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img8.jpg', 'спорт8', 'футбол'),
(9, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img9.jpg', 'спорт9', 'футбол'),
(10, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img10.jpg', 'спорт10', 'футбол'),
(11, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img11.jpg', 'спорт11', 'бокс'),
(12, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img12.jpg', 'спорт12', 'бокс'),
(13, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img13.jpg', 'спорт13', 'бокс'),
(14, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img14.jpg', 'спорт14', 'бокс'),
(15, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img15.jpg', 'спорт15', 'бокс'),
(16, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img16.jpg', 'спорт16', 'бокс'),
(17, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img17.jpg', 'спорт17', 'бокс'),
(18, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img18.jpg', 'спорт18', 'бокс'),
(19, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img19.jpg', 'спорт19', 'бокс'),
(20, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img20.jpg', 'спорт20', 'бокс'),
(21, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img21.jpg', 'спорт21', 'шахматы'),
(22, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img22.jpg', 'спорт22', 'шахматы'),
(23, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img23.jpg', 'спорт23', 'шахматы'),
(24, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img24.jpg', 'спорт24', 'шахматы'),
(25, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img25.jpg', 'спорт25', 'шахматы'),
(26, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img26.jpg', 'спорт26', 'шахматы'),
(27, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem...', '@web/images/img27.jp', 'спорт27', 'шахматы'),
(28, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem...', '@web/images/img28.jp', 'спорт28', 'шахматы'),
(29, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem...', '@web/images/img29.jp', 'спорт29', 'шахматы'),
(30, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem...', '@web/images/img30.jp', 'спорт30', 'шахматы'),
(31, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem...', '@web/images/img31.jp', 'спорт31', 'шахматы'),
(32, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img1.jpg', 'политика1', 'президет'),
(33, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img2.jpg', 'политика2', 'президет'),
(34, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img3.jpg', 'политика3', 'президет'),
(35, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img4.jpg', 'политика4', 'президет'),
(36, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img5.jpg', 'политика5', 'президет'),
(37, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img6.jpg', 'политика6', 'президет'),
(38, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img7.jpg', 'политика7', 'президет'),
(39, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img8.jpg', 'политика8', 'президет'),
(40, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img9.jpg', 'политика9', 'президет'),
(41, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img10.jpg', 'политика10', 'президет'),
(42, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img11.jpg', 'политика11', 'президет'),
(43, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img12.jpg', 'политика12', 'президет'),
(44, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img13.jpg', 'политика13', 'революция'),
(45, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img14.jpg', 'политика14', 'революция'),
(46, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img15.jpg', 'политика15', 'революция'),
(47, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img16.jpg', 'политика16', 'революция'),
(48, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img17.jpg', 'политика17', 'революция'),
(49, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img18.jpg', 'политика18', 'революция'),
(50, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img19.jpg', 'политика19', 'революция'),
(51, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img20.jpg', 'политика20', 'революция'),
(52, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img21.jpg', 'политика21', 'революция'),
(53, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img22.jpg', 'политика22', 'революция'),
(54, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img23.jpg', 'политика23', 'революция'),
(55, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem...', '@web/images/img24.jpg', 'политика24', 'революция'),
(56, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem...', '@web/images/img25.jpg', 'политика25', 'революция'),
(57, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem...', '@web/images/img26.jpg', 'политика26', 'выборы'),
(58, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem...', '@web/images/img27.jpg', 'политика27', 'выборы'),
(59, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem...', '@web/images/img28.jpg', 'политика28', 'выборы'),
(60, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem...', '@web/images/img29.jpg', 'политика29', 'выборы'),
(61, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem...', '@web/images/img30.jpg', 'политика30', 'выборы'),
(62, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem...', '@web/images/img31.jpg', 'политика31', 'выборы');
INSERT INTO `news` (`id`, `category`, `text`, `analityc`, `description`, `img`, `name`, `tags`) VALUES
(63, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem...', '@web/images/img32.jpg', 'политика32', 'выборы'),
(64, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem...', '@web/images/img33.jpg', 'политика33', 'выборы'),
(65, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem...', '@web/images/img34.jpg', 'политика34', 'выборы'),
(66, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem...', '@web/images/img35.jpg', 'политика35', 'выборы'),
(67, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem...', '@web/images/img36.jpg', 'политика36', 'выборы'),
(68, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem...', '@web/images/img37.jpg', 'политика37', 'выборы'),
(69, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem...', '@web/images/img38.jpg', 'политика38', 'выборы'),
(70, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem...', '@web/images/img39.jpg', 'политика39', 'выборы'),
(71, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem...', '@web/images/img40.jpg', 'политика40', 'выборы'),
(72, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem...', '@web/images/img32.jpg', 'спорт32', 'выборы'),
(73, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem...', '@web/images/img33.jpg', 'спорт33', 'выборы'),
(74, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem...', '@web/images/img34.jpg', 'спорт34', 'выборы'),
(75, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem...', '@web/images/img35.jpg', 'спорт35', 'выборы'),
(76, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem...', '@web/images/img36.jpg', 'спорт36', 'выборы'),
(77, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem...', '@web/images/img37.jpg', 'спорт37', 'выборы');

--
-- Индексы сохранённых таблиц
--

--
-- Индексы таблицы `news`
--
ALTER TABLE `news`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT для сохранённых таблиц
--

--
-- AUTO_INCREMENT для таблицы `news`
--
ALTER TABLE `news`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=78;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
