-- phpMyAdmin SQL Dump
-- version 4.6.5.2
-- https://www.phpmyadmin.net/
--
-- Хост: 127.0.0.1
-- Время создания: Июл 14 2017 г., 16:35
-- Версия сервера: 10.1.21-MariaDB
-- Версия PHP: 5.6.30

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- База данных: `module4`
--

-- --------------------------------------------------------

--
-- Структура таблицы `comments`
--

CREATE TABLE `comments` (
  `id` int(11) NOT NULL,
  `username` varchar(50) NOT NULL,
  `text` text NOT NULL,
  `count` int(11) DEFAULT NULL,
  `subject` varchar(50) NOT NULL,
  `date` varchar(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Дамп данных таблицы `comments`
--

INSERT INTO `comments` (`id`, `username`, `text`, `count`, `subject`, `date`) VALUES
(35, 'Tolik', 'some message1', 2, 'спорт37', '13 July 2017 02:51:46'),
(36, 'Vasia', 'some messag2', NULL, 'спорт37', '13 July 2017 02:52:46'),
(37, 'Vasia', 'some messag2', NULL, 'спорт37', '13 July 2017 02:54:14'),
(38, 'Taras', 'message', 3, 'спорт36', '13 July 2017 02:52:46'),
(39, 'Taras', 'message', 1, 'спорт35', '13 July 2017 02:53:46'),
(40, 'Taras', 'message1', 1, 'спорт35', '13 July 2017 02:54:46'),
(41, 'Taras', 'message2', 6, 'спорт35', '13 July 2017 02:55:46'),
(42, 'Taras', 'message3', 2, 'спорт35', '13 July 2017 02:55:46'),
(43, 'Taras', 'message4', 4, 'спорт34', '13 July 2017 02:56:46'),
(44, 'Taras', 'message5', 3, 'спорт34', '13 July 2017 02:57:46'),
(45, 'Taras', 'message6', 3, 'спорт34', '14 July 2017 02:58:46'),
(46, 'Taras', 'message7', 6, 'спорт33', '13 July 2017 02:59:46'),
(47, 'Taras', 'message8', 7, 'спорт33', '15 July 2017 02:52:40'),
(48, 'Kolia', 'message', 1, 'спорт33', '13 July 2017 02:52:41'),
(49, 'Kolia', 'message', 1, 'спорт32', '13 July 2017 02:52:42'),
(50, 'Kolia', 'message', 1, 'спорт32', '13 July 2017 02:52:43'),
(51, 'Kolia', 'message', 2, 'спорт31', '13 July 2017 02:52:44'),
(52, 'Sasha', 'message', 3, 'спорт31', '13 July 2017 02:52:45'),
(53, 'Sasha', 'message', 6, 'спорт30', '13 July 2017 02:52:50'),
(54, 'Sasha', 'message', 3, 'спорт30', '13 July 2017 02:52:32'),
(55, 'Vlad', 'text', NULL, 'спорт29', '13 July 2017 03:54:14'),
(56, 'Vlad', 'text1', NULL, 'спорт29', '13 July 2017 03:54:14'),
(57, 'Vlad', 'text2', NULL, 'спорт28', '13 July 2017 03:50:14'),
(58, 'Vasia', 'some messag2', NULL, 'спорт37', '13 July 2017 03:03:22'),
(59, 'Vasia', 'some messag2', NULL, 'спорт37', '13 July 2017 03:04:46'),
(60, 'Vasia', 'some messag2', NULL, 'спорт37', '13 July 2017 03:05:29'),
(61, 'Vasia', 'some messag2', NULL, 'спорт37', '13 July 2017 03:06:08'),
(62, 'Vasia', 'привет', NULL, 'спорт37', '13 July 2017 03:13:31'),
(63, 'Vasia', 'привет', NULL, 'спорт37', '13 July 2017 03:14:09'),
(64, 'Vasia', 'привет', NULL, 'спорт37', '13 July 2017 03:14:15'),
(65, 'Vasia', 'hello', NULL, 'спорт37', '13 July 2017 03:16:52'),
(66, 'Vasia', 'hello2', NULL, 'спорт37', '13 July 2017 03:17:10');

-- --------------------------------------------------------

--
-- Структура таблицы `news`
--

CREATE TABLE `news` (
  `id` int(11) NOT NULL,
  `category` varchar(50) NOT NULL,
  `text` text NOT NULL,
  `analityc` tinyint(1) DEFAULT NULL,
  `description` text,
  `img` varchar(50) NOT NULL,
  `name` varchar(50) NOT NULL,
  `tags1` varchar(250) NOT NULL,
  `tags2` varchar(250) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Дамп данных таблицы `news`
--

INSERT INTO `news` (`id`, `category`, `text`, `analityc`, `description`, `img`, `name`, `tags1`, `tags2`) VALUES
(1, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img1.jpg', 'спорт1', 'футбол', 'победа'),
(2, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img2.jpg', 'спорт2', 'футбол', 'победа'),
(3, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img3.jpg', 'спорт3', 'футбол', 'победа'),
(4, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img4.jpg', 'спорт4', 'футбол', 'победа'),
(5, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img5.jpg', 'спорт5', 'футбол', 'победа'),
(6, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img6.jpg', 'спорт6', 'футбол', 'поражение'),
(7, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img7.jpg', 'спорт7', 'футбол', 'поражение'),
(8, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img8.jpg', 'спорт8', 'футбол', 'поражение'),
(9, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img9.jpg', 'спорт9', 'футбол', 'поражение'),
(10, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img10.jpg', 'спорт10', 'футбол', 'поражение'),
(11, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img11.jpg', 'спорт11', 'бокс', 'поражение'),
(12, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img12.jpg', 'спорт12', 'бокс', 'поражение'),
(13, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img13.jpg', 'спорт13', 'бокс', 'поражение'),
(14, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img14.jpg', 'спорт14', 'бокс', 'поражение'),
(15, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img15.jpg', 'спорт15', 'бокс', 'соперники'),
(16, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img16.jpg', 'спорт16', 'бокс', 'соперники'),
(17, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img17.jpg', 'спорт17', 'бокс', 'соперники'),
(18, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img18.jpg', 'спорт18', 'бокс', 'соперники'),
(19, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img19.jpg', 'спорт19', 'бокс', 'соперники'),
(20, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img20.jpg', 'спорт20', 'бокс', 'соперники'),
(21, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img21.jpg', 'спорт21', 'шахматы', 'соперники'),
(22, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img22.jpg', 'спорт22', 'шахматы', 'соперники'),
(23, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img23.jpg', 'спорт23', 'шахматы', 'соперники'),
(24, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img24.jpg', 'спорт24', 'шахматы', 'победа'),
(25, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img25.jpg', 'спорт25', 'шахматы', 'победа'),
(26, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img26.jpg', 'спорт26', 'шахматы', 'победа'),
(27, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem...', '@web/images/img27.jpg', 'спорт27', 'шахматы', 'победа'),
(28, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem...', '@web/images/img28.jpg', 'спорт28', 'шахматы', 'победа'),
(29, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem...', '@web/images/img29.jpg', 'спорт29', 'шахматы', 'победа'),
(30, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem...', '@web/images/img30.jpg', 'спорт30', 'шахматы', 'победа'),
(31, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem...', '@web/images/img31.jpg', 'спорт31', 'шахматы', 'победа'),
(32, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img1.jpg', 'политика1', 'президент', 'покращення'),
(33, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img2.jpg', 'политика2', 'президент', 'покращення'),
(34, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img3.jpg', 'политика3', 'президент', 'покращення'),
(35, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img4.jpg', 'политика4', 'президент', 'покращення'),
(36, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img5.jpg', 'политика5', 'президент', 'покращення'),
(37, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img6.jpg', 'политика6', 'президент', 'покращення'),
(38, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img7.jpg', 'политика7', 'президент', 'покращення'),
(39, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img8.jpg', 'политика8', 'президент', 'покращення'),
(40, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img9.jpg', 'политика9', 'президент', 'покращення'),
(41, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img10.jpg', 'политика10', 'президент', 'надежда'),
(42, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img11.jpg', 'политика11', 'президент', 'надежда'),
(43, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img12.jpg', 'политика12', 'президент', 'надежда'),
(44, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img13.jpg', 'политика13', 'революция', 'надежда'),
(45, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img14.jpg', 'политика14', 'революция', 'надежда'),
(46, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img15.jpg', 'политика15', 'революция', 'надежда'),
(47, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img16.jpg', 'политика16', 'революция', 'надежда'),
(48, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img17.jpg', 'политика17', 'революция', 'надежда'),
(49, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img18.jpg', 'политика18', 'революция', 'надежда'),
(50, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img19.jpg', 'политика19', 'революция', 'надежда'),
(51, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img20.jpg', 'политика20', 'революция', 'соперники'),
(52, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img21.jpg', 'политика21', 'революция', 'соперники'),
(53, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img22.jpg', 'политика22', 'революция', 'соперники'),
(54, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img23.jpg', 'политика23', 'революция', 'соперники'),
(55, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem...', '@web/images/img24.jpg', 'политика24', 'революция', 'соперники'),
(56, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem...', '@web/images/img25.jpg', 'политика25', 'революция', 'соперники'),
(57, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem...', '@web/images/img26.jpg', 'политика26', 'выборы', 'соперники'),
(58, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem...', '@web/images/img27.jpg', 'политика27', 'выборы', 'соперники'),
(59, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem...', '@web/images/img28.jpg', 'политика28', 'выборы', 'соперники'),
(60, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem...', '@web/images/img29.jpg', 'политика29', 'выборы', 'соперники'),
(61, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem...', '@web/images/img30.jpg', 'политика30', 'выборы', 'победа');
INSERT INTO `news` (`id`, `category`, `text`, `analityc`, `description`, `img`, `name`, `tags1`, `tags2`) VALUES
(62, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem...', '@web/images/img31.jpg', 'политика31', 'выборы', 'победа'),
(63, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem...', '@web/images/img32.jpg', 'политика32', 'выборы', 'победа'),
(64, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem...', '@web/images/img33.jpg', 'политика33', 'выборы', 'победа'),
(65, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem...', '@web/images/img34.jpg', 'политика34', 'выборы', 'победа'),
(66, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem...', '@web/images/img35.jpg', 'политика35', 'выборы', 'победа'),
(67, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem...', '@web/images/img36.jpg', 'политика36', 'выборы', 'победа'),
(68, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem...', '@web/images/img37.jpg', 'политика37', 'выборы', 'победа'),
(69, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem...', '@web/images/img8.jpg', 'политика38', 'выборы', 'поражение'),
(70, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem...', '@web/images/img29.jpg', 'политика39', 'выборы', 'поражение'),
(71, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem...', '@web/images/img4.jpg', 'политика40', 'выборы', 'поражение'),
(72, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem...', '@web/images/img32.jpg', 'спорт32', 'выборы', 'поражение'),
(73, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem...', '@web/images/img33.jpg', 'спорт33', 'выборы', 'поражение'),
(74, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem...', '@web/images/img34.jpg', 'спорт34', 'выборы', 'поражение'),
(75, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem...', '@web/images/img35.jpg', 'спорт35', 'выборы', 'поражение'),
(76, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem...', '@web/images/img36.jpg', 'спорт36', 'выборы', 'поражение'),
(77, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem...', '@web/images/img37.jpg', 'спорт37', 'выборы', 'поражение');

-- --------------------------------------------------------

--
-- Структура таблицы `reclame`
--

CREATE TABLE `reclame` (
  `id` int(11) NOT NULL,
  `name` varchar(250) NOT NULL,
  `price` int(11) NOT NULL,
  `firm` varchar(250) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Дамп данных таблицы `reclame`
--

INSERT INTO `reclame` (`id`, `name`, `price`, `firm`) VALUES
(1, 'телефон', 5000, 'самсунг'),
(2, 'планшет', 3000, 'лг'),
(3, 'ноутбук', 6000, 'асус'),
(4, 'телевизор', 5050, 'филипс'),
(5, 'ремонт квартир', 60000, 'строимдом'),
(6, 'установка окон', 10050, 'окна'),
(7, 'ремонт машин', 20000, 'СТО'),
(8, 'монтаж дверей', 12050, 'двери');

-- --------------------------------------------------------

--
-- Структура таблицы `users`
--

CREATE TABLE `users` (
  `id` int(11) NOT NULL,
  `name` varchar(50) NOT NULL,
  `email` varchar(50) NOT NULL,
  `password` varchar(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Дамп данных таблицы `users`
--

INSERT INTO `users` (`id`, `name`, `email`, `password`) VALUES
(1, 'Tolik', 'dt150685@mail.ru', '40bd001563085fc35165329ea1ff5c5ecbdbbeef'),
(2, 'admin', 'admin@admin.com', 'd033e22ae348aeb5660fc2140aec35850c4da997'),
(3, 'Kolia', 'kolia@kolia.com', '40bd001563085fc35165329ea1ff5c5ecbdbbeef'),
(4, 'Vasia', 'vasia@vasia.com', '40bd001563085fc35165329ea1ff5c5ecbdbbeef'),
(5, 'Sasha', 'sasha@sasha.com', '40bd001563085fc35165329ea1ff5c5ecbdbbeef'),
(6, 'Taras', 'taras@taras.com', '40bd001563085fc35165329ea1ff5c5ecbdbbeef'),
(7, 'Vlad', 'vlad@vlad.com', '40bd001563085fc35165329ea1ff5c5ecbdbbeef'),
(8, 'Olia', 'olia@olia.com', '40bd001563085fc35165329ea1ff5c5ecbdbbeef');

--
-- Индексы сохранённых таблиц
--

--
-- Индексы таблицы `comments`
--
ALTER TABLE `comments`
  ADD PRIMARY KEY (`id`),
  ADD KEY `sub` (`subject`),
  ADD KEY `username` (`username`);

--
-- Индексы таблицы `news`
--
ALTER TABLE `news`
  ADD PRIMARY KEY (`id`),
  ADD KEY `category` (`category`),
  ADD KEY `name` (`name`);

--
-- Индексы таблицы `reclame`
--
ALTER TABLE `reclame`
  ADD PRIMARY KEY (`id`);

--
-- Индексы таблицы `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`id`),
  ADD KEY `name` (`name`);

--
-- AUTO_INCREMENT для сохранённых таблиц
--

--
-- AUTO_INCREMENT для таблицы `comments`
--
ALTER TABLE `comments`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=87;
--
-- AUTO_INCREMENT для таблицы `news`
--
ALTER TABLE `news`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=78;
--
-- AUTO_INCREMENT для таблицы `reclame`
--
ALTER TABLE `reclame`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=9;
--
-- AUTO_INCREMENT для таблицы `users`
--
ALTER TABLE `users`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=9;
--
-- Ограничения внешнего ключа сохраненных таблиц
--

--
-- Ограничения внешнего ключа таблицы `comments`
--
ALTER TABLE `comments`
  ADD CONSTRAINT `comments_ibfk_1` FOREIGN KEY (`username`) REFERENCES `users` (`name`),
  ADD CONSTRAINT `comments_ibfk_2` FOREIGN KEY (`subject`) REFERENCES `news` (`name`);

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
