-- phpMyAdmin SQL Dump
-- version 4.6.5.2
-- https://www.phpmyadmin.net/
--
-- Хост: 127.0.0.1
-- Время создания: Июл 10 2017 г., 23:11
-- Версия сервера: 10.1.21-MariaDB
-- Версия PHP: 5.6.30

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- База данных: `module4`
--

-- --------------------------------------------------------

--
-- Структура таблицы `news`
--

CREATE TABLE `news` (
  `id` int(11) NOT NULL,
  `category` varchar(50) NOT NULL,
  `text` text NOT NULL,
  `analityc` tinyint(1) DEFAULT NULL,
  `description` text,
  `img` varchar(50) NOT NULL,
  `name` varchar(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Дамп данных таблицы `news`
--

INSERT INTO `news` (`id`, `category`, `text`, `analityc`, `description`, `img`, `name`) VALUES
(1, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img1.jpg', 'спорт1'),
(2, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img2.jpg', 'спорт2'),
(3, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img3.jpg', 'спорт3'),
(4, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img4.jpg', 'спорт4'),
(5, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img5.jpg', 'спорт5'),
(6, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img6.jpg', 'спорт6'),
(7, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img7.jpg', 'спорт7'),
(8, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img8.jpg', 'спорт8'),
(9, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img9.jpg', 'спорт9'),
(10, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img10.jpg', 'спорт10'),
(11, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img11.jpg', 'спорт11'),
(12, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img12.jpg', 'спорт12'),
(13, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img13.jpg', 'спорт13'),
(14, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img14.jpg', 'спорт14'),
(15, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img15.jpg', 'спорт15'),
(16, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img16.jpg', 'спорт16'),
(17, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img17.jpg', 'спорт17'),
(18, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img18.jpg', 'спорт18'),
(19, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img19.jpg', 'спорт19'),
(20, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img20.jpg', 'спорт20'),
(21, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img21.jpg', 'спорт21'),
(22, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img22.jpg', 'спорт22'),
(23, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img23.jpg', 'спорт23'),
(24, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img24.jpg', 'спорт24'),
(25, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img25.jpg', 'спорт25'),
(26, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img26.jpg', 'спорт26'),
(27, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem...', '@web/images/img27.jp', 'спорт27'),
(28, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem...', '@web/images/img28.jp', 'спорт28'),
(29, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem...', '@web/images/img29.jp', 'спорт29'),
(30, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem...', '@web/images/img30.jp', 'спорт30'),
(31, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem...', '@web/images/img31.jp', 'спорт31'),
(32, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img1.jpg', 'политика1'),
(33, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img2.jpg', 'политика2'),
(34, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img3.jpg', 'политика3'),
(35, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img4.jpg', 'политика4'),
(36, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img5.jpg', 'политика5'),
(37, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img6.jpg', 'политика6'),
(38, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img7.jpg', 'политика7'),
(39, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img8.jpg', 'политика8'),
(40, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img9.jpg', 'политика9'),
(41, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img10.jpg', 'политика10'),
(42, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img11.jpg', 'политика11'),
(43, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img12.jpg', 'политика12'),
(44, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img13.jpg', 'политика13'),
(45, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img14.jpg', 'политика14'),
(46, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img15.jpg', 'политика15'),
(47, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img16.jpg', 'политика16'),
(48, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img17.jpg', 'политика17'),
(49, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img18.jpg', 'политика18'),
(50, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img19.jpg', 'политика19'),
(51, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img20.jpg', 'политика20'),
(52, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img21.jpg', 'политика21'),
(53, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img22.jpg', 'политика22'),
(54, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', NULL, NULL, '@web/images/img23.jpg', 'политика23'),
(55, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem...', '@web/images/img24.jpg', 'политика24'),
(56, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem...', '@web/images/img25.jpg', 'политика25'),
(57, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem...', '@web/images/img26.jpg', 'политика26'),
(58, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem...', '@web/images/img27.jpg', 'политика27'),
(59, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem...', '@web/images/img28.jpg', 'политика28'),
(60, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem...', '@web/images/img29.jpg', 'политика29'),
(61, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem...', '@web/images/img30.jpg', 'политика30'),
(62, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem...', '@web/images/img31.jpg', 'политика31'),
(63, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem...', '@web/images/img32.jpg', 'политика32');
INSERT INTO `news` (`id`, `category`, `text`, `analityc`, `description`, `img`, `name`) VALUES
(64, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem...', '@web/images/img33.jpg', 'политика33'),
(65, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem...', '@web/images/img34.jpg', 'политика34'),
(66, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem...', '@web/images/img35.jpg', 'политика35'),
(67, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem...', '@web/images/img36.jpg', 'политика36'),
(68, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem...', '@web/images/img37.jpg', 'политика37'),
(69, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem...', '@web/images/img38.jpg', 'политика38'),
(70, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem...', '@web/images/img39.jpg', 'политика39'),
(71, 'Политика', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem...', '@web/images/img40.jpg', 'политика40'),
(72, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem...', '@web/images/img32.jp', 'спорт32'),
(73, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem...', '@web/images/img33.jp', 'спорт33'),
(74, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem...', '@web/images/img34.jp', 'спорт34'),
(75, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem...', '@web/images/img35.jp', 'спорт35'),
(76, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem...', '@web/images/img36.jp', 'спорт36'),
(77, 'Спорт', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem. Quisque pharetra nisi et ipsum fringilla, vel vestibulum felis maximus. Nulla sollicitudin urna et purus placerat ullamcorper. Sed vel dictum massa. Integer metus metus, vulputate eu efficitur sed, elementum sit amet enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et massa pretium, ornare nulla at, pretium dolor. Nam imperdiet erat id est suscipit, sed tincidunt nisi consequat. Praesent nec fermentum diam.', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec suscipit risus. Pellentesque venenatis augue sed justo euismod lacinia. In dui orci, luctus consectetur nibh in, mattis hendrerit lorem...', '@web/images/img37.jp', 'спорт37');

--
-- Индексы сохранённых таблиц
--

--
-- Индексы таблицы `news`
--
ALTER TABLE `news`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT для сохранённых таблиц
--

--
-- AUTO_INCREMENT для таблицы `news`
--
ALTER TABLE `news`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=78;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
